#Here place only admin routes!!!

#PROFILE MANAGE
admin.admin:
    pattern:    /
    defaults:   { _controller: McmsDashboardBundle:Dashboard:index, roleTheme: Admin}

admin.profile:
    pattern:    /profile
    defaults:   { _controller: McmsUserBundle:User:profile, roleTheme: Admin }

admin.editProfile:
    pattern:    /profile/edit
    defaults:   { _controller: McmsUserBundle:User:editProfile, roleTheme: Admin }

admin.updateProfile:
    pattern:    /profile/update
    defaults:   { _controller: McmsUserBundle:User:updateProfile, roleTheme: Admin }
    requirements:
        _method:    POST

admin.changePassword:
    pattern:    /profile/changePassword
    defaults:   { _controller: McmsUserBundle:User:changePassword, roleTheme: Admin }

admin.updatePassword:
    pattern:    /profile/updatePassword
    defaults:   { _controller: McmsUserBundle:User:updatePassword, roleTheme: Admin}

# MANAGE PRODUCTS
admin.productList:
    pattern:    /products/{page}
    defaults:   { _controller: McmsProductBundle:Product:list, page: 1, roleTheme: Admin }

admin.productNew:
    pattern:    /product/new
    defaults:  { _controller: McmsProductBundle:Product:new }

admin.productCreate:
    pattern:    /product/create
    defaults:   { _controller: McmsProductBundle:Product:create }
    requirements:
        _method:    POST

admin.productShow:
    pattern:   /product/{id}/show
    defaults:  { _controller: McmsProductBundle:Product:show, roleTheme: Admin }
    requirements:
        id:   \d+

admin.productEdit:
    pattern:   /product/{id}/edit
    defaults:  { _controller: McmsProductBundle:Product:edit }
    requirements:
        id:   \d+

admin.productUpdate:
    pattern:    /product/{id}/update
    defaults:   { _controller: McmsProductBundle:Product:update }
    requirements:
        _method:    POST
        id: \d+

admin.productDelete:
    pattern:   /product/{id}/delete
    defaults:  { _controller: McmsProductBundle:Product:delete }
    requirements:
        _method:  POST
        id:   \d+

#EMPLOYEES
admin.employeeList:
    pattern: /employees
    defaults: { _controller: McmsEmployeeBundle:Employee:list, roleTheme: Admin }

admin.employeeShow:
    pattern: /employee/{employeeId}/show
    defaults: { _controller: McmsEmployeeBundle:Employee:show, roleTheme: Admin }
    requirements:
        employeeId: \d+

admin.employeeNew:
    pattern: /employee/new
    defaults: { _controller: McmsEmployeeBundle:Employee:new }

admin.employeeCreate:
    pattern: /employee/create
    defaults: { _controller: McmsEmployeeBundle:Employee:create }
    requirements:
        _method: POST

#MANAGE USERS
users_list:
    pattern: /users
    defaults: { _controller: McmsUserBundle:Manage:usersList }

user_show:
    pattern: /user/{id}/show
    defaults: { _controller: McmsUserBundle:Manage:userShow }
    requirements:
        id: \d+

admin.userEdit:
    pattern: /user/{userId}/edit
    defaults: { _controller: McmsUserBundle:User:edit }
    requirements:
        userId: \d+

admin.userUpdate:
    pattern: /user/{userId}/update
    defaults: { _controller: McmsUserBundle:User:update }
    requirements:
        userId: \d+
        _method: POST

user_password_reset:
    pattern: /user/{id}/password_reset
    defaults: { _controller: McmsUserBundle:Manage:userPasswordReset }
    requirements:
        _method: POST
        id: \d+

admin.myTimetable:
    pattern: /myTimetable
    defaults: { _controller: McmsTimetableBundle:Timetable:myMonthlyTimetable, roleTheme: Admin, year: null, month: null }

admin.ajax:
    pattern: /loadMyTimetable
    defaults: { _controller: McmsTimetableBundle:Timetable:renderMonth, roleTheme: Admin, year: null, month: null }
