#Here place only admin routes!!!

#PROFILE MANAGE
admin.profile:
    pattern:    /profile
    defaults:   { _controller: McmsUserBundle:User:profile, roleTheme: Admin }

admin.editProfile:
    pattern:    /profile/edit
    defaults:   { _controller: McmsUserBundle:User:editProfile, roleTheme: Admin }

admin.updateProfile:
    pattern:    /profile/update
    defaults:   { _controller: McmsUserBundle:User:updateProfile, roleTheme: Admin }
    requirements:
        _method:    POST

admin.changePassword:
    pattern:    /profile/changePassword
    defaults:   { _controller: McmsUserBundle:User:changePassword, roleTheme: Admin }

admin.updatePassword:
    pattern:    /profile/updatePassword
    defaults:   { _controller: McmsUserBundle:User:updatePassword, roleTheme: Admin}

# MANAGE PRODUCTS
admin.productList:
    pattern:    /products/{page}
    defaults:   { _controller: McmsProductBundle:Product:list, page: 1, roleTheme: Admin }

admin.productNew:
    pattern:    /product/new
    defaults:  { _controller: McmsProductBundle:Product:new }

admin.productCreate:
    pattern:    /product/create
    defaults:   { _controller: McmsProductBundle:Product:create }
    requirements:
        _method:    POST

admin.productShow:
    pattern:   /product/{id}/show
    defaults:  { _controller: McmsProductBundle:Product:show, roleTheme: Admin }
    requirements:
        id:   \d+

admin.productEdit:
    pattern:   /product/{id}/edit
    defaults:  { _controller: McmsProductBundle:Product:edit }
    requirements:
        id:   \d+

admin.productUpdate:
    pattern:    /product/{id}/update
    defaults:   { _controller: McmsProductBundle:Product:update }
    requirements:
        _method:    POST
        id: \d+

admin.productDelete:
    pattern:   /product/{id}/delete
    defaults:  { _controller: McmsProductBundle:Product:delete }
    requirements:
        _method:  POST
        id:   \d+


#MANAGE USERS
users_list:
    pattern: /users
    defaults: { _controller: McmsUserBundle:Manage:usersList }

user_show:
    pattern: /user/{id}/show
    defaults: { _controller: McmsUserBundle:Manage:userShow }
    requirements:
        id: \d+

user_password_reset:
    pattern: /user/{id}/password_reset
    defaults: { _controller: McmsUserBundle:Manage:userPasswordReset }
    requirements:
        _method: POST
        id: \d+