#Here place only admin routes!!!

# MANAGE PRODUCTS
admin.productList:
    pattern:    /product
    defaults:   { _controller: McmsProductBundle:Product:list, roleTheme: Admin }

admin.productNew:
    pattern:    /product/new
    defaults:  { _controller: McmsProductBundle:Product:new }

admin.productCreate:
    pattern:    /product/create
    defaults:   { _controller: McmsProductBundle:Product:create }
    requirements:
        _method:    POST

admin.productShow:
    pattern:   /product/{id}/show
    defaults:  { _controller: McmsProductBundle:Product:show, roleTheme: Admin }
    requirements:
        id:   \d+

admin.productEdit:
    pattern:   /product/{id}/edit
    defaults:  { _controller: McmsProductBundle:Product:edit }
    requirements:
        id:   \d+

admin.productUpdate:
    pattern:    /product/{id}/update
    defaults:   { _controller: McmsProductBundle:Product:update }
    requirements:
        _method:    POST
        id: \d+

admin.productDelete:
    pattern:   /product/{id}/delete
    defaults:  { _controller: McmsProductBundle:Product:delete }
    requirements:
        _method:  POST
        id:   \d+


#MANAGE USERS
users_list:
    pattern: /users
    defaults: { _controller: McmsUserBundle:Manage:usersList }

user_show:
    pattern: /user/{id}/show
    defaults: { _controller: McmsUserBundle:Manage:userShow }
    requirements:
        id: \d+

user_password_reset:
    pattern: /user/{id}/password_reset
    defaults: { _controller: McmsUserBundle:Manage:userPasswordReset }
    requirements:
        _method: POST
        id: \d+