#Here place only employee routes!!!

#PROFILE MANAGE
employee.profile:
    pattern:    /profile
    defaults:   { _controller: McmsUserBundle:User:profile, roleTheme: Employee }

employee.editProfile:
    pattern:    /profile/edit
    defaults:   { _controller: McmsUserBundle:User:editProfile, roleTheme: Employee }

employee.updateProfile:
    pattern:    /profile/update
    defaults:   { _controller: McmsUserBundle:User:updateProfile, roleTheme: Employee }
    requirements:
        _method:    POST

employee.changePassword:
    pattern:    /profile/changePassword
    defaults:   { _controller: McmsUserBundle:User:changePassword, roleTheme: Employee }

employee.updatePassword:
    pattern:    /profile/updatePassword
    defaults:   { _controller: McmsUserBundle:User:updatePassword, roleTheme: Employee}

#PATIENTS
employee.patientList:
    pattern: /patients
    defaults: { _controller: McmsPatientBundle:Patient:list, roleTheme: Employee }

employee.patientShow:
    pattern: /patient/{patientId}/show
    defaults: { _controller: McmsPatientBundle:Patient:show, roleTheme: Employee }
    requirements:
        patientId: \d+

employee.patientNew:
    pattern: /patient/new
    defaults: { _controller: McmsPatientBundle:Patient:new }

employee.patientCreate:
    pattern: /patient/create
    defaults: { _controller: McmsPatientBundle:Patient:create }
    requirements:
        _method: POST

#MEDICAL HISTORY
employee.medicalHistory:
    pattern: /patient/{patientId}/medicalHistory
    defaults: { _controller: McmsMedicalHistoryBundle:MedicalHistory:list, roleTheme: Employee }
    requirements:
        patientId: \d+

employee.medicalHistoryNew:
    pattern: /patient/{patientId}/medicalHistory/new
    defaults: { _controller: McmsMedicalHistoryBundle:MedicalHistory:new, roleTheme: Employee }
    requirements:
        patientId: \d+

employee.medicalHistoryCreate:
    pattern: /patient/{patientId}/medicalHistory/create
    defaults: { _controller: McmsMedicalHistoryBundle:MedicalHistory:create, roleTheme: Employee }
    requirements:
        patientId: \d+
        _method:    POST

employee.medicalHistoryShow:
    pattern: /patient/{patientId}/medicalHistory/{entryId}/show
    defaults: { _controller: McmsMedicalHistoryBundle:MedicalHistory:show, roleTheme: Employee }
    requirements:
        patientId: \d+
        entryId: \d+

employee.medicalHistoryEdit:
    pattern: /patient/{patientId}/medicalHistory/{entryId}/edit
    defaults: { _controller: McmsMedicalHistoryBundle:MedicalHistory:edit, roleTheme: Employee }
    requirements:
        patientId: \d+
        entryId: \d+

employee.medicalHistoryUpdate:
    pattern: /patient/{patientId}/medicalHistory/{entryId}/update
    defaults: { _controller: McmsMedicalHistoryBundle:MedicalHistory:update, roleTheme: Employee }
    requirements:
        patientId: \d+
        entryId: \d+
        _method:    POST

#PAYMENTS
employee.paymentNew:
    pattern: /payment/new
    defaults: { _controller: McmsPaymentBundle:Payment:new }

employee.paymentCreate:
    pattern: /payment/create
    defaults: { _controller: McmsPaymentBundle:Payment:create }
    requirements:
        _method:    POST