#Here place only patient routes!!!
patient.listOfEmployees:
    pattern: /listOfEmployees
    defaults: { _controller: McmsDashboardBundle:Patient:listOfEmployees }

patient.showEmployee:
    pattern: /employee/{id}/show
    defaults: { _controller: McmsDashboardBundle:Patient:showEmployee }
    requirements:
        id: \d+

patient.showEmployeeTimetable:
    pattern: /employee/{employeeId}/timetable/{year}/{month}
    defaults: { _controller: McmsTimetableBundle:Timetable:monthlyTimetable, roleTheme: Patient, year: null, month: null, patientId: null, employeeId: null }
    requirements:
        id: \d+
        year: \d+
        month: \d+

patient.showTimetable:
    pattern: /timetable/{year}/{month}
    defaults: { _controller: McmsTimetableBundle:Timetable:myMonthlyTimetable, roleTheme: Patient, year: null, month: null }

patient.showMyAccount:
    pattern: /myAccount
    defaults: { _controller: McmsDashboardBundle:Patient:showMyAccount }

patient.productsList:
    pattern: /product
    defaults: { _controller: McmsProductBundle:Product:list, roleTheme: Patient }

patient.timetableNew:
    pattern: /employee/{employeeId}/timetable/new
    defaults: { _controller: McmsTimetableBundle:Timetable:new, roleTheme: Patient, patientId: null, date: null }