#Routes for administrator only.
AdminRoutes:
    resource: "admin_routes.yml"
    prefix:   /admin

#Routes for patient only.
PatientRoutes:
    resource: "patient_routes.yml"
    prefix:   /patient

#Routes for employee only.
EmployeeRoutes:
    resource: "employee_routes.yml"
    prefix:   /employee




McmsDashboardBundle:
    resource: "@McmsDashboardBundle/Controller/"
    type:     annotation
    prefix:   /

McmsPaymentBundle:
    resource: "@McmsPaymentBundle/Controller/"
    type:     annotation
    prefix:   /

McmsMedicalHistoryBundle:
    resource: "@McmsMedicalHistoryBundle/Controller/"
    type:     annotation
    prefix:   /

McmsTimetableBundle:
    resource: "@McmsTimetableBundle/Controller/"
    type:     annotation
    prefix:   /

McmsProductBundle:
    resource: "@McmsProductBundle/Controller/"
    type:     annotation
    prefix:   /

McmsEmployeeBundle:
    resource: "@McmsEmployeeBundle/Controller/"
    type:     annotation
    prefix:   /

McmsPatientBundle:
    resource: "@McmsPatientBundle/Controller/"
    type:     annotation
    prefix:   /

McmsUserBundle:
    resource: "@McmsUserBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern: /login
    defaults: { _controller: McmsUserBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

admin_dashboard:
    pattern: /patient/new

patient_edit:
    pattern: /patient/edit
    defaults: { _controller: McmsPatientBundle:Account:edit }

patient_update:
    pattern: /patient/update
    defaults:  { _controller: McmsPatientBundle:Account:update }

changePassword:
    pattern: /change_password
    defaults: { _controller: McmsUserBundle:Account:changePassword }
    requirements:
        _method:  GET

changePasswordProcess:
    pattern: /change_password
    defaults: { _controller: McmsUserBundle:Account:changePasswordProcess }
    requirements:
        _method:  POST

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
