<?php

namespace Mcms\MedicalHistoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Mcms\PatientBundle\Entity\Patient;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    /**
     * Finds and returns entries by Patient.
     * 
     * @param Patient $patient
     */
    public function findByPatient(Patient $patient)
    {
        return $this->findBy(array(
            'patient' => $patient->getId()
        ));
    }

    /**
     * Finds and returns single entry by Patient and entry Id.
     * 
     * @param Patient $patient
     * @param integer $entryId
     */
    public function findByPatientAndId(Patient $patient, $entryId)
    {
        return $this->findBy(array(
            'patient' => $patient->getId(),
            'id' => $entryId
        ));
    }
}