<?php

namespace Mcms\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends EntityRepository
{
}