<?php

namespace Mcms\PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentProductRepository extends EntityRepository
{
}